
version: 2

models:
  - name: stg_BankA
    description: "Stg table that houses BankA seed data"
    columns:
      - name: trans_ID
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
  - name: stg_BankB
    description: "Stg table that houses BankB seed data"
    columns:
      - name: trans_ID
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
