
version: 2

models:
  - name: fct_BankA
    description: "Fact table that houses BankA seed data"
    columns:
      - name: trans_ID
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
